# Generated by Django 2.0.4 on 2018-04-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishcollectionrecord',
            options={'verbose_name': 'fish', 'verbose_name_plural': 'fishes'},
        ),
    ]
