# Generated by Django 2.0.4 on 2018-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_auto_20180420_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv/')),
            ],
            options={
                'verbose_name': 'CSV Document',
                'verbose_name_plural': 'CSV Documents',
            },
        ),
    ]
